/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorIndicator: typeof import('./src/components/ColorIndicator.vue')['default']
    ColorInput: typeof import('./src/components/ColorInput.vue')['default']
    ConfirmationDialog: typeof import('./src/components/ConfirmationDialog.vue')['default']
    DueIndicator: typeof import('./src/components/DueIndicator.vue')['default']
    HomeworkCard: typeof import('./src/components/HomeworkCard.vue')['default']
    HomeworkDialog: typeof import('./src/components/HomeworkDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubjectDialog: typeof import('./src/components/SubjectDialog.vue')['default']
    SubjectIndicator: typeof import('./src/components/SubjectIndicator.vue')['default']
  }
}
