volumes:
  pg_data:

services:
  database:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: homeworks
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: homeworks
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      timeout: 5s
      start_interval: 0s
      interval: 1s
      retries: 5

  homeworks:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://homeworks:test1234@database:5432/homeworks"
    depends_on:
      database:
        condition: service_healthy
