FROM mcr.microsoft.com/playwright:v1.51.1-noble

WORKDIR /app/frontend

RUN npm install -g pnpm

COPY ./frontend/package.json ./frontend/pnpm-lock.yaml /app/frontend/

RUN pnpm install

COPY ./frontend/ /app/frontend

CMD [ "pnpm", "exec", "playwright", "test" ]
