CREATE TABLE subjects (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  name VARCHAR NOT NULL
);

ALTER TABLE homeworks
ADD subject_id INTEGER REFERENCES subjects(id) ON DELETE SET NULL;
