CREATE TABLE files (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  s3_key VARCHAR NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  homework_id INTEGER NOT NULL REFERENCES homeworks(id) ON DELETE CASCADE
);
